development:
  adapter: postgresql
  database: scoretognos_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: scoretognos_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: scoretognos_production
  pool: 5
  timeout: 5000
